package com.lilithsthrone.game.sex.positions.slots;

/**
 * @since 0.3.4
 * @version 0.3.9
 * @author Innoxia
 */
public enum SexSlotTag {
	
	STANDING,
	STANDING_BEHIND,
	PERFORMING_ORAL,
	PERFORMING_ORAL_BEHIND,

	FACE_TO_WALL,
	BACK_TO_WALL,
	
	SITTING,
	SITTING_IN_LAP,
	SITTING_BETWEEN_LEGS,
	SITTING_PERFORMING_ORAL,
	SITTING_TAUR_PRESENTING_ORAL,
	
	OVER_DESK_FRONT,
	OVER_DESK_BACK,
	OVER_DESK_BETWEEN_LEGS,
	
	ALL_FOURS,
	BEHIND_ALL_FOURS,
	
	LYING_DOWN,
	LYING_DOWN_ON_FRONT,
	COWGIRL,
	COWGIRL_REVERSE,
	FACE_SITTING,
	FACE_SITTING_REVERSE,
	RECEIVING_ORAL_FROM_PRONE_PARTNER,
	LAP_PILLOW,
	MISSIONARY,
	MISSIONARY_ORAL,
	SIXTY_NINE,
	MATING_PRESS,
	SCISSORING,
	
	LOCKED_IN_STOCKS,
	BEHIND_STOCKS,
	HUMPING_STOCKS,
	PERFORMING_ORAL_STOCKS,
	RECEIVING_ORAL_STOCKS;
}
