package com.lilithsthrone.game.dialogue.encounters;

/**
 * @since 0.1.69.9
 * @version 0.2.3
 * @author Innoxia
 */
public enum EncounterType {

	SPECIAL_DOMINION_CULTIST,
	
	SLAVE_USES_YOU,
	
	DOMINION_STREET_FIND_HAPPINESS, // Kinariu
	
	DOMINION_FIND_ITEM,
	DOMINION_FIND_CLOTHING,
	DOMINION_FIND_WEAPON,

	DOMINION_ALLEY_ATTACK,
	DOMINION_STORM_ATTACK,
	
	HARPY_NEST_ATTACK,
	HARPY_NEST_ATTACK_STORM,
	HARPY_NEST_FIND_ITEM,
	
	SUBMISSION_TUNNEL_ATTACK,
	SUBMISSION_FIND_ITEM,

	BAT_CAVERN_BAT_ATTACK,
	BAT_CAVERN_SLIME_ATTACK,
	BAT_CAVERN_FIND_ITEM
	;
}
